### PR TITLE
Database GET requests for account details 

### PR DESCRIPTION
**Pull request by swolbean**
This gives get requests for the following

- All account details 
- Name
- Password
- Postcode
- Scan Count

### CODE REVIEW

**Comment by swolbean** [comment]
EDIT: To test the functions:
localhost:numbers/api/get-accountdetails-<db-column>/<email> 

i.e. To test getting the name:
localhost:5000/api/get-accountdetails-name/Jane.doe@someemail.com

**Comment by tam-debug** [comment]
Populated account details - looks kinda sad but it should work.
Commented out the edit button since the functionality isn't there. (I swear it was there before though)

image


Also included post code as a field in the sign up
image

**Comment by tam-debug** [comment]
image

**Review by ClodaghMM — APPROVED** [review]
Thank you both for completing this work. Approving after seeing your screenshots and code.

**Pull request merged**
