### PR TITLE
Counter Page Creation

### PR DESCRIPTION
**Pull request by swolbean**
Installed libraries:
- react-virtuoso (virtualisation compatiability for table)
- material-ui 
- react-router-dom
 
Modified page(s): 
- Counter.js
- Common.css
- App.js (Added route)

Modified Folder(s):
- ./images (added another folder to hold dummy images for table [./images/dummy photos)

### CODE REVIEW

**Comment by tam-debug** [comment]
Looking good, idk if it's possible but could the scan history go below the count when the window is resized?
image

**Comment by swolbean** [comment]
> Looking good, idk if it's possible but could the scan history go below the count when the window is resized? image

just amended this as per requirements :D thank you

**Comment by tam-debug** [comment]
Sorry for being picky but could the green gradient background extend for the whole page?

image

**Review by tam-debug — APPROVED** [review]
Looks good

**Pull request merged**
